USE PROJETO;

##MAX->TRAZ O VALOR MÁXIMO DA COLUNA
SELECT MAX(HORA) as 'MAIOR VALOR' FROM CURSOS;

SELECT NOME, VALOR, HORA FROM CURSOS WHERE VALOR = (SELECT MAX(VALOR) as 'MAIOR VALOR' FROM CURSOS);

SELECT * FROM CURSOS;