-- inicio das procedures
CREATE DATABASE PROJETO;
USE PROJETO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY auto_increment,
    NOME VARCHAR(30) NOT NULL,
    HORA INT(3) NOT NULL, 
    VALOR FLOAT(10,1) NOT NULL
);
SHOW TABLES;

INSERT INTO CURSOS VALUES (NULL, 'JAVA', 30, 500.00);
INSERT INTO CURSOS VALUES (NULL, 'JAVASCRIPT', 54, 1000.00);
SELECT * FROM CURSOS;

DELIMITER #

##CRIANDO UMA PROCEDURE
CREATE PROCEDURE CAD_CURSO(NOME_CURSO VARCHAR(30), HORAS_CURSO INT, VALOR_CURSO FLOAT(10.1))
BEGIN
INSERT INTO CURSOS VALUES (NULL,NOME_CURSO, HORAS_CURSO, VALOR_CURSO);
END
#

DELIMITER ;
CALL CAD_CURSO('COBOL', 5, 20.5);

## MISSÃO, CRIAR PROCEDURE PARA CONSULTAR CURSOS
