-- criação de view
CREATE VIEW RELATORIO AS
SELECT CLIENTE.IDCLIENTE,
    CLIENTE.NOME,
    CLIENTE.EMAIL,
    CLIENTE.SEXO,
    CLIENTE.CPF,
    TELEFONE.NUMERO,
    ENDERECO.CIDADE,
    ENDERECO.BAIRRO,
    ENDERECO.ESTADO
FROM CLIENTE
    INNER JOIN TELEFONE ON TELEFONE.ID_CLIENTE = CLIENTE.IDCLIENTE
    INNER JOIN ENDERECO ON ENDERECO.ID_CLIENTE = CLIENTE.IDCLIENTE;